version: "3"
services:
    app:
      build: .
      depends_on:
        - mariadb
      ports:
        - "8000:80"
      volumes:
        - .:/srv/app
      links:
        - mariadb:mariadb
    mariadb:
      image: mariadb:10.1.21
      ports:
        - "13307:3306"
      environment:
        - MYSQL_DATABASE=authors
        - MYSQL_ROOT_PASSWORD=password